spring:
  application:
    name: sheRide


  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 7200
  refreshTokenExpiration: 604800
